version: "3.7"

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    command: python /usr/src/app/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - postgres
  postgres:
    image: postgres:10.5-alpine
    volumes:
      - pg-data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

volumes:
  pg-data: