version: "3.7"

x-app: &app
  build:
    context: .
    dockerfile: Dockerfile
  volumes:
    - ./src/:/usr/src/app/
  env_file:
    - ./.env
  depends_on:
    - postgres
    - redis

services:
  django:
    <<: *app
    command: python /usr/src/app/manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000

  celery:
    <<: *app
    command: celery -A config worker -l info

  postgres:
    image: postgres:10.5-alpine
    volumes:
      - pg-data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  redis:
    image: redis:alpine

volumes:
  pg-data: