# Generated by Django 3.1.7 on 2021-03-26 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("project", "0001_initial"),
        ("user_platform", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="platform",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                related_query_name="projects",
                to="user_platform.userplatform",
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.UniqueConstraint(
                fields=("platform", "external_id"), name="platform_external_id_uniq"
            ),
        ),
    ]
