# Generated by Django 3.1.7 on 2021-03-29 22:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("dependency", "0004_auto_20210329_2228"),
        ("project", "0002_auto_20210329_2034"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectDependency",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.CharField(max_length=63)),
                (
                    "source_file",
                    models.CharField(
                        choices=[
                            ("requirements.txt", "requirements.txt"),
                            ("Pipfile.lock", "Pipfile.lock"),
                            ("package-lock.json", "package-lock.json"),
                            ("yarn.lock", "yarn.lock"),
                        ],
                        max_length=63,
                    ),
                ),
                (
                    "dependency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        related_query_name="versions",
                        to="dependency.dependency",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependencies",
                        related_query_name="dependencies",
                        to="project.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
