# Generated by Django 3.1.7 on 2021-03-26 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user_platform", "0001_initial"),
        ("project", "0002_auto_20210326_1351"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="platform",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                related_query_name="projects",
                to="user_platform.userplatform",
            ),
        ),
    ]
