# Generated by Django 3.1.7 on 2021-03-31 21:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name_plural': 'Dependencies',
            },
        ),
    ]
