# Generated by Django 3.1.7 on 2021-03-29 20:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dependency",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("source_file", models.CharField(max_length=127)),
                ("language", models.CharField(max_length=15)),
            ],
            options={
                "verbose_name_plural": "Dependencies",
            },
        ),
        migrations.CreateModel(
            name="DependencyVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.CharField(max_length=63)),
                (
                    "dependency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        related_query_name="versions",
                        to="dependency.dependency",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
