# Generated by Django 3.1.7 on 2021-03-22 20:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dependency",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("version", models.CharField(max_length=31)),
                ("from_file", models.CharField(max_length=127)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dependencies",
                        related_query_name="dependencies",
                        to="project.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
