# Generated by Django 3.1.7 on 2021-04-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dependency', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='dependency',
            constraint=models.UniqueConstraint(fields=('name', 'language'), name='name_language_uniq'),
        ),
    ]
