# Generated by Django 3.1.7 on 2021-03-29 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("project", "0001_initial"),
        ("dependency", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dependencyversion",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dependencies",
                related_query_name="dependencies",
                to="project.project",
            ),
        ),
    ]
