# Generated by Django 3.1.7 on 2021-03-29 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dependency", "0002_dependencyversion_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dependency",
            name="source_file",
            field=models.CharField(blank=True, default="", max_length=127),
        ),
    ]
