# Generated by Django 3.1.7 on 2021-03-26 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dependency", "0002_dependency_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dependency",
            name="version",
            field=models.CharField(max_length=63),
        ),
    ]
