# Generated by Django 3.1.7 on 2021-03-29 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dependency", "0003_auto_20210329_2125"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dependency",
            name="source_file",
        ),
        migrations.DeleteModel(
            name="DependencyVersion",
        ),
    ]
